version: "1"

services:
  ms-btpn-test-server:
    build:
      context: .
    container_name: ms-btpn-test-server
    image: ms-btpn-test-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URL=mongodb://host.docker.internal:27017/books
    volumes:
      - ./logs:/logs
    networks:
      - app-network
    ports:
      - "8000:8000"

networks:
  app-network:
    driver: bridge